services:
  db:
    image: postgres:16-alpine               # hivatalos, minimal image
    environment:
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: tasker
      POSTGRES_DB: tasker
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # ez kell legyen itt :contentReference[oaicite:2]{index=2}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgres://tasker:tasker@db:5432/tasker
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
