name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: tasker
          POSTGRES_PASSWORD: tasker
          POSTGRES_DB: tasker
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U tasker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -U tasker; do
            sleep 1
          done

      - name: Apply database schema
        run: |
          psql -h localhost -U tasker -d tasker -f db/init.sql

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Lint code
        run: |
          pip install flake8
          flake8 .
